/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1b1b1c",
        "surface-container-low": "#1c1b1b",
        "secondary": "#c8c6c5",
        "on-tertiary-container": "#f8f9ff",
        "secondary-container": "#474746",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#001b3c",
        "primary": "#ffb4aa",
        "surface-container-high": "#2a2a2a",
        "inverse-primary": "#c0000c",
        "on-secondary-fixed-variant": "#474746",
        "primary-fixed": "#ffdad5",
        "on-primary": "#690003",
        "inverse-surface": "#e5e2e1",
        "on-secondary-container": "#b7b5b4",
        "on-surface-variant": "#e9bcb6",
        "on-secondary": "#303030",
        "surface-container-lowest": "#0e0e0e",
        "primary-fixed-dim": "#ffb4aa",
        "on-background": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-tint": "#ffb4aa",
        "on-primary-fixed-variant": "#930007",
        "on-tertiary-fixed-variant": "#004689",
        "outline": "#af8782",
        "on-primary-fixed": "#410001",
        "on-tertiary": "#003061",
        "tertiary-fixed": "#d5e3ff",
        "on-error-container": "#ffdad6",
        "surface-variant": "#353534",
        "outline-variant": "#5e3f3b",
        "surface-container-highest": "#353534",
        "surface": "#131313",
        "tertiary-fixed-dim": "#a7c8ff",
        "inverse-on-surface": "#313030",
        "surface-container": "#201f1f",
        "primary-container": "#e50914",
        "tertiary-container": "#0072d7",
        "surface-bright": "#393939",
        "background": "#131313",
        "secondary-fixed": "#e5e2e1",
        "tertiary": "#a7c8ff",
        "on-error": "#690005",
        "on-surface": "#e5e2e1",
        "error": "#ffb4ab",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "container-margin": "1rem",
        "space-sm": "1rem",
        "grid-gutter": "1rem",
        "space-xl": "3rem",
        "space-xs": "0.75rem",
        "space-md": "1.5rem",
        "space-lg": "2rem",
        "space-2xs": "0.5rem",
        "space-3xs": "0.25rem"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
